In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from matplotlib.colors import ListedColormap

In [2]:
wine_df = pd.read_csv('data/wine.csv')
wine_df.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [3]:
X = wine_df.iloc[:, 1:12].values
X

array([[14.23,  1.71,  2.43, ...,  2.29,  5.64,  1.04],
       [13.2 ,  1.78,  2.14, ...,  1.28,  4.38,  1.05],
       [13.16,  2.36,  2.67, ...,  2.81,  5.68,  1.03],
       ...,
       [13.27,  4.28,  2.26, ...,  1.35, 10.2 ,  0.59],
       [13.17,  2.59,  2.37, ...,  1.46,  9.3 ,  0.6 ],
       [14.13,  4.1 ,  2.74, ...,  1.35,  9.2 ,  0.61]])

In [4]:
Y = wine_df.iloc[:,0].values
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state = 0)

In [6]:
X_train

array([[13.69,  3.26,  2.54, ...,  0.8 ,  5.88,  0.96],
       [12.69,  1.53,  2.26, ...,  1.62,  3.05,  0.96],
       [11.62,  1.99,  2.28, ...,  1.35,  3.25,  1.16],
       ...,
       [12.42,  1.61,  2.19, ...,  1.61,  2.06,  1.06],
       [13.9 ,  1.68,  2.12, ...,  2.14,  6.1 ,  0.91],
       [14.16,  2.51,  2.48, ...,  1.24,  9.7 ,  0.62]])

In [7]:
X_test

array([[ 13.74,   1.67,   2.25,  16.4 , 118.  ,   2.6 ,   2.9 ,   0.21,
          1.62,   5.85,   0.92],
       [ 12.79,   2.67,   2.48,  22.  , 112.  ,   1.48,   1.36,   0.24,
          1.26,  10.8 ,   0.48],
       [ 12.37,   1.13,   2.16,  19.  ,  87.  ,   3.5 ,   3.1 ,   0.19,
          1.87,   4.45,   1.22],
       [ 13.56,   1.73,   2.46,  20.5 , 116.  ,   2.96,   2.78,   0.2 ,
          2.45,   6.25,   0.98],
       [ 13.05,   5.8 ,   2.13,  21.5 ,  86.  ,   2.62,   2.65,   0.3 ,
          2.01,   2.6 ,   0.73],
       [ 11.56,   2.05,   3.23,  28.5 , 119.  ,   3.18,   5.08,   0.47,
          1.87,   6.  ,   0.93],
       [ 14.06,   2.15,   2.61,  17.6 , 121.  ,   2.6 ,   2.51,   0.31,
          1.25,   5.05,   1.06],
       [ 12.36,   3.83,   2.38,  21.  ,  88.  ,   2.3 ,   0.92,   0.5 ,
          1.04,   7.65,   0.56],
       [ 12.25,   1.73,   2.12,  19.  ,  80.  ,   1.65,   2.03,   0.37,
          1.63,   3.4 ,   1.  ],
       [ 12.08,   1.83,   2.32,  18.5 ,  81.  ,   1.6 ,

In [8]:
y_train

array([3, 2, 2, 3, 1, 1, 2, 2, 2, 1, 3, 2, 3, 1, 3, 3, 1, 3, 1, 2, 3, 3,
       2, 3, 3, 1, 2, 3, 2, 2, 3, 2, 1, 2, 2, 2, 1, 1, 2, 2, 3, 3, 2, 2,
       2, 3, 3, 1, 3, 2, 2, 2, 2, 2, 1, 1, 2, 1, 3, 1, 3, 1, 1, 2, 1, 2,
       2, 1, 3, 2, 1, 2, 2, 2, 3, 1, 3, 3, 1, 1, 2, 3, 1, 1, 2, 2, 1, 1,
       1, 3, 2, 1, 2, 3, 1, 2, 3, 3, 1, 1, 3, 1, 3, 2, 1, 1, 2, 1, 3, 2,
       3, 1, 3, 3, 3, 1, 2, 2, 2, 2, 3, 3, 2, 2, 1, 2, 3, 3, 1, 1, 3, 2,
       2, 2, 1, 1, 1, 2, 2, 2, 1, 3], dtype=int64)

In [9]:
y_test

array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 3, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1], dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [11]:
x_train = sc.fit_transform(X_train)
print('x_train đã chuẩn hóa=', x_train)

x_train đã chuẩn hóa= [[ 0.87668336  0.79842885  0.64412971 ... -1.36820277  0.35193216
   0.0290166 ]
 [-0.36659076 -0.7581304  -0.39779858 ...  0.02366802 -0.84114577
   0.0290166 ]
 [-1.69689407 -0.34424759 -0.32337513 ... -0.4346309  -0.75682931
   0.90197362]
 ...
 [-0.70227477 -0.68615078 -0.65828065 ...  0.00669399 -1.25851226
   0.46549511]
 [ 1.13777093 -0.62316862 -0.91876272 ...  0.90631778  0.44468027
  -0.18922266]
 [ 1.4610222   0.12361993  0.42085937 ... -0.62134527  1.96237659
  -1.45501034]]


In [12]:
x_test = sc.transform(X_test)
print('x_test đã chuẩn hóa=',x_test)

x_test đã chuẩn hóa= [[ 9.38847070e-01 -6.32166068e-01 -4.35010303e-01 -9.19695615e-01
   1.26324041e+00  5.59998633e-01  9.77754158e-01 -1.20637533e+00
   2.36680192e-02  3.39284695e-01 -1.45574805e-01]
 [-2.42263344e-01  2.67579163e-01  4.20859365e-01  7.12764102e-01
   8.40672358e-01 -1.27747161e+00 -6.05828120e-01 -9.70634096e-01
  -5.87397203e-01  2.42611713e+00 -2.06608025e+00]
 [-7.64438475e-01 -1.11802849e+00 -7.69915825e-01 -1.61767889e-01
  -9.20027861e-01  2.03653722e+00  1.18341419e+00 -1.36353615e+00
   4.48018868e-01 -2.50930538e-01  1.16386073e+00]
 [ 7.15057728e-01 -5.78181354e-01  3.46435916e-01  2.75498106e-01
   1.12238439e+00  1.15061407e+00  8.54358136e-01 -1.28495574e+00
   1.43251284e+00  5.07917619e-01  1.16312302e-01]
 [ 8.09879269e-02  3.08378173e+00 -8.81550999e-01  5.67008770e-01
  -9.90455870e-01  5.92810602e-01  7.20679112e-01 -4.99151627e-01
   6.85655343e-01 -1.03085781e+00 -9.74883977e-01]
 [-1.77149051e+00 -2.90262880e-01  3.21173872e+00  2.60758342e+0

In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)

In [14]:
x_train = pca.fit_transform(x_train)
print('x_train_pca=',x_train)

x_train_pca= [[-2.01075908  0.78266023  0.09277129  0.15578232 -1.17554816]
 [-1.3926999  -1.70798365 -0.25263976 -1.19258131 -0.23444947]
 [ 1.54268973 -1.61243699 -0.18738002  0.54401335  0.1739341 ]
 [-2.37598257  1.3323925  -0.07610043  0.26076881  0.37607132]
 [ 1.23287337  0.09705667 -0.84156277 -0.37217456 -0.68900319]
 [ 2.18999755  1.21593183 -1.66129752 -0.5954166  -0.25999003]
 [ 1.12520827 -1.52829733 -0.04470192 -0.20268017  1.01577763]
 [-0.22737688 -2.46626065  1.22572812  0.17685863 -0.36899958]
 [ 0.25191397 -2.03262667 -1.44651149 -0.44203298 -0.45014705]
 [ 1.77585983  1.43589017  0.53114581  0.83005388 -0.02359864]
 [-2.70643807 -0.34968686  1.00005935 -0.58943885 -0.34147744]
 [ 1.83371819 -1.13419895 -0.64879752  0.73782736  0.21219236]
 [-2.19735742  0.42881845  1.51750911  1.67507538  0.63975869]
 [ 1.77534167  2.18307943 -0.85066801  0.26899298 -0.82794498]
 [-1.67748348 -0.03146267  0.70163269  1.24192619 -0.5143889 ]
 [-2.80132479 -0.09430339  1.00789005 -0.9

In [15]:
x_test = pca.transform(x_test)
print('x_test_pca=',x_train)

x_test_pca= [[-2.01075908  0.78266023  0.09277129  0.15578232 -1.17554816]
 [-1.3926999  -1.70798365 -0.25263976 -1.19258131 -0.23444947]
 [ 1.54268973 -1.61243699 -0.18738002  0.54401335  0.1739341 ]
 [-2.37598257  1.3323925  -0.07610043  0.26076881  0.37607132]
 [ 1.23287337  0.09705667 -0.84156277 -0.37217456 -0.68900319]
 [ 2.18999755  1.21593183 -1.66129752 -0.5954166  -0.25999003]
 [ 1.12520827 -1.52829733 -0.04470192 -0.20268017  1.01577763]
 [-0.22737688 -2.46626065  1.22572812  0.17685863 -0.36899958]
 [ 0.25191397 -2.03262667 -1.44651149 -0.44203298 -0.45014705]
 [ 1.77585983  1.43589017  0.53114581  0.83005388 -0.02359864]
 [-2.70643807 -0.34968686  1.00005935 -0.58943885 -0.34147744]
 [ 1.83371819 -1.13419895 -0.64879752  0.73782736  0.21219236]
 [-2.19735742  0.42881845  1.51750911  1.67507538  0.63975869]
 [ 1.77534167  2.18307943 -0.85066801  0.26899298 -0.82794498]
 [-1.67748348 -0.03146267  0.70163269  1.24192619 -0.5143889 ]
 [-2.80132479 -0.09430339  1.00789005 -0.92

In [16]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)


In [17]:
#train model
classifier.fit(x_train, y_train)
#predicting results
y_pred = classifier.predict(x_test)

In [18]:
print("accuracy score:", accuracy_score(y_test,y_pred))

accuracy score: 0.9722222222222222


In [19]:
print(classification_report(y_test, y_pred, digits=4))

              precision    recall  f1-score   support

           1     0.9333    1.0000    0.9655        14
           2     1.0000    0.9375    0.9677        16
           3     1.0000    1.0000    1.0000         6

    accuracy                         0.9722        36
   macro avg     0.9778    0.9792    0.9778        36
weighted avg     0.9741    0.9722    0.9723        36



In [20]:
print(confusion_matrix(y_test, y_pred))

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
