In [91]:
import numpy as np
import pandas as pd

In [92]:
wine_df = pd.read_csv('data/wine.csv')
wine_df.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [93]:
x = wine_df.iloc[:,1:12].values
x

array([[14.23,  1.71,  2.43, ...,  2.29,  5.64,  1.04],
       [13.2 ,  1.78,  2.14, ...,  1.28,  4.38,  1.05],
       [13.16,  2.36,  2.67, ...,  2.81,  5.68,  1.03],
       ...,
       [13.27,  4.28,  2.26, ...,  1.35, 10.2 ,  0.59],
       [13.17,  2.59,  2.37, ...,  1.46,  9.3 ,  0.6 ],
       [14.13,  4.1 ,  2.74, ...,  1.35,  9.2 ,  0.61]])

In [94]:
y = wine_df.iloc[:,0].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [95]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [96]:
X_train

array([[13.71,  1.86,  2.36, ...,  1.69,  3.8 ,  1.11],
       [12.22,  1.29,  1.94, ...,  2.08,  2.7 ,  0.86],
       [13.27,  4.28,  2.26, ...,  1.35, 10.2 ,  0.59],
       ...,
       [12.42,  1.61,  2.19, ...,  1.61,  2.06,  1.06],
       [13.9 ,  1.68,  2.12, ...,  2.14,  6.1 ,  0.91],
       [14.16,  2.51,  2.48, ...,  1.24,  9.7 ,  0.62]])

In [97]:
X_test

array([[1.374e+01, 1.670e+00, 2.250e+00, 1.640e+01, 1.180e+02, 2.600e+00,
        2.900e+00, 2.100e-01, 1.620e+00, 5.850e+00, 9.200e-01],
       [1.279e+01, 2.670e+00, 2.480e+00, 2.200e+01, 1.120e+02, 1.480e+00,
        1.360e+00, 2.400e-01, 1.260e+00, 1.080e+01, 4.800e-01],
       [1.237e+01, 1.130e+00, 2.160e+00, 1.900e+01, 8.700e+01, 3.500e+00,
        3.100e+00, 1.900e-01, 1.870e+00, 4.450e+00, 1.220e+00],
       [1.356e+01, 1.730e+00, 2.460e+00, 2.050e+01, 1.160e+02, 2.960e+00,
        2.780e+00, 2.000e-01, 2.450e+00, 6.250e+00, 9.800e-01],
       [1.305e+01, 5.800e+00, 2.130e+00, 2.150e+01, 8.600e+01, 2.620e+00,
        2.650e+00, 3.000e-01, 2.010e+00, 2.600e+00, 7.300e-01],
       [1.156e+01, 2.050e+00, 3.230e+00, 2.850e+01, 1.190e+02, 3.180e+00,
        5.080e+00, 4.700e-01, 1.870e+00, 6.000e+00, 9.300e-01],
       [1.406e+01, 2.150e+00, 2.610e+00, 1.760e+01, 1.210e+02, 2.600e+00,
        2.510e+00, 3.100e-01, 1.250e+00, 5.050e+00, 1.060e+00],
       [1.236e+01, 3.830e+00, 2.38

In [98]:
y_train

array([1, 2, 3, 3, 2, 3, 3, 1, 2, 3, 2, 2, 3, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       3, 3, 2, 2, 2, 3, 3, 1, 3, 2, 2, 2, 2, 2, 1, 1, 2, 1, 3, 1, 3, 1,
       1, 2, 1, 2, 2, 1, 3, 2, 1, 2, 2, 2, 3, 1, 3, 3, 1, 1, 2, 3, 1, 1,
       2, 2, 1, 1, 1, 3, 2, 1, 2, 3, 1, 2, 3, 3, 1, 1, 3, 1, 3, 2, 1, 1,
       2, 1, 3, 2, 3, 1, 3, 3, 3, 1, 2, 2, 2, 2, 3, 3, 2, 2, 1, 2, 3, 3,
       1, 1, 3, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 3], dtype=int64)

In [99]:
y_test

array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 3, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1, 3, 2, 2, 3, 1, 1, 2, 2,
       2, 1, 3, 2, 3, 1, 3, 3, 1, 3], dtype=int64)

In [100]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [101]:
#standardize the data
x_train = sc.fit_transform(X_train)
x_train

array([[ 0.91083058, -0.46259897, -0.01142613, ...,  0.13007174,
        -0.51238741,  0.65706596],
       [-0.95609928, -0.96608672, -1.53725357, ...,  0.78462633,
        -0.98210744, -0.40859506],
       [ 0.35952243,  1.67501572, -0.37471838, ..., -0.44056558,
         2.22052913, -1.55950896],
       ...,
       [-0.70550467, -0.68342693, -0.62902295, ..., -0.00419586,
        -1.25539909,  0.44393375],
       [ 1.14889546, -0.6215951 , -0.88332752, ...,  0.88532703,
         0.46975447, -0.19546286],
       [ 1.47466845,  0.11155374,  0.42452457, ..., -0.62518354,
         2.00702002, -1.43162964]])

In [102]:
x_test = sc.transform(X_test)
x_test

array([[ 0.94841977, -0.63042822, -0.4110476 , -0.87677804,  1.22679643,
         0.57147571,  0.95620726, -1.24682729,  0.01258759,  0.36299992,
        -0.15283642],
       [-0.24190464,  0.25288364,  0.42452457,  0.69400284,  0.81583896,
        -1.30214437, -0.62636631, -1.00437054, -0.59161664,  2.47674005,
        -2.02839981],
       [-0.76815332, -1.10741662, -0.73801062, -0.14748691, -0.89648384,
         2.07706327,  1.16173629, -1.40846512,  0.43217386, -0.23482557,
         1.1259568 ],
       [ 0.72288462, -0.57742951,  0.35186612,  0.27325796,  1.08981061,
         1.17371073,  0.83288984, -1.3276462 ,  1.40561401,  0.5338072 ,
         0.10292223],
       [ 0.08386836,  3.01764974, -0.8469983 ,  0.55375455, -0.96497675,
         0.60493321,  0.69929597, -0.51945706,  0.66714217, -1.02480926,
        -0.96273879],
       [-1.7830615 , -0.29476971,  3.14921644,  2.51723066,  1.29528934,
         1.54174325,  3.19647374,  0.85446449,  0.43217386,  0.42705265,
        -0.110

In [103]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)

In [104]:
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [105]:
y_pred = classifier.predict(x_test)

In [106]:
from sklearn.metrics import accuracy_score
print("accuracy score:", accuracy_score(y_test,y_pred))

accuracy score: 0.9814814814814815


In [107]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, digits=4))

              precision    recall  f1-score   support

           1     0.9500    1.0000    0.9744        19
           2     1.0000    0.9545    0.9767        22
           3     1.0000    1.0000    1.0000        13

    accuracy                         0.9815        54
   macro avg     0.9833    0.9848    0.9837        54
weighted avg     0.9824    0.9815    0.9815        54



In [108]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[19  0  0]
 [ 1 21  0]
 [ 0  0 13]]
